# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#181B1B"

# Main text color
theme[main_fg]="#E7DECD"

# Title color for boxes
theme[title]="#E7DECD"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#E67E80"

# Background color of selected items
theme[selected_bg]="#2D353B"

# Foreground color of selected items
theme[selected_fg]="#FAF4ED"

# Color of inactive/disabled text
theme[inactive_fg]="#56635F"  

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#E7DECD"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#A7C080"

# Cpu box outline color
theme[cpu_box]="#E67E80"

# Memory/disks box outline color
theme[mem_box]="#DBBC7F"

# Net up/down box outline color
theme[net_box]="#A7C080"

# Processes box outline color
theme[proc_box]="#7FBBB3"

# Box divider line and small boxes line color
theme[div_line]="#2D353B"

# Temperature graph colors
theme[temp_start]="#A7C080"
theme[temp_mid]="#DBBC7F"
theme[temp_end]="#E67E80"

# CPU graph colors
theme[cpu_start]="#A7C080"
theme[cpu_mid]="#DBBC7F"
theme[cpu_end]="#E67E80"

# Mem/Disk free meter
theme[free_start]="#E67E80"
theme[free_mid]="#DBBC7F"
theme[free_end]="#A7C080"

# Mem/Disk cached meter
theme[cached_start]="#7FBBB3"
theme[cached_mid]="#83C092"
theme[cached_end]="#A7C080"

# Mem/Disk available meter
theme[available_start]="#E67E80"
theme[available_mid]="#DBBC7F"
theme[available_end]="#A7C080"

# Mem/Disk used meter
theme[used_start]="#A7C080"
theme[used_mid]="#DBBC7F"
theme[used_end]="#E67E80"

# Download graph colors
theme[download_start]="#A7C080"
theme[download_mid]="#83C092"
theme[download_end]="#7FBBB3"

# Upload graph colors
theme[upload_start]="#DBBC7F"
theme[upload_mid]="#E69875"
theme[upload_end]="#E67E80"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#A7C080"
theme[process_mid]="#D699B6"
theme[process_end]="#E67E80"
