background = #181B1B
background-opacity = 0.90
foreground = #E7DECD
cursor-color = #E7DECD
selection-background = #2D353B
selection-foreground = #FAF4ED

palette = 0=#232A2E
palette = 1=#E67E80
palette = 2=#A7C080
palette = 3=#DBBC7F
palette = 4=#7FBBB3
palette = 5=#D699B6
palette = 6=#83C092
palette = 7=#E7DECD
palette = 8=#56635F
palette = 9=#F18F91
palette = 10=#B7D090
palette = 11=#E7C78B
palette = 12=#8FCAC2
palette = 13=#E3A8C3
palette = 14=#98D1A6
palette = 15=#FAF4ED
