foreground            #E7DECD
background            #181B1B
background_opacity    0.90
selection_foreground  #FAF4ED
selection_background  #2D353B

cursor                #E7DECD
cursor_text_color     #181B1B

active_border_color   #A7C080
active_tab_background #A7C080

color0  #232A2E
color8  #56635F
color1  #E67E80
color9  #F18F91
color2  #A7C080
color10 #B7D090
color3  #DBBC7F
color11 #E7C78B
color4  #7FBBB3
color12 #8FCAC2
color5  #D699B6
color13 #E3A8C3
color6  #83C092
color14 #98D1A6
color7  #E7DECD
color15 #FAF4ED
